Downloading Time Series exchange_rate data set...
rse = 0.45590422646200524
Loading data from ./data/exchange_rate12/train.tfrecords
Loading model with fresh parameters
# of trainable parameters: 4915501
Downloading Time Series exchange_rate data set...
rse = 0.45590422646200524
Loading data from ./data/exchange_rate12/validation.tfrecords
Epoch: 1
Stop
Traceback (most recent call last):
  File "/home/isabella/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/isabella/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/isabella/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: x.  Can't parse serialized Example.
	 [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_FLOAT, DT_FLOAT], dense_keys=["x", "y"], dense_shapes=[[16,8], [8]], num_sparse=0, sparse_keys=[], sparse_types=[]](arg0, ParseSingleExample/Const, ParseSingleExample/Const)]]
	 [[Node: model/input/IteratorGetNext = IteratorGetNext[output_shapes=[[?,16,8], [?], [?,16,8]], output_types=[DT_FLOAT, DT_INT32, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/input/Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 23, in main
    train(para, sess, model, data_generator)
  File "/home/isabella/Documents/5331/TPA-LSTM/lib/train.py", line 26, in train
    [loss, global_step, _] = sess.run(fetches=[model.loss, model.global_step, model.update])
  File "/home/isabella/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/isabella/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/isabella/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/isabella/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: x.  Can't parse serialized Example.
	 [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_FLOAT, DT_FLOAT], dense_keys=["x", "y"], dense_shapes=[[16,8], [8]], num_sparse=0, sparse_keys=[], sparse_types=[]](arg0, ParseSingleExample/Const, ParseSingleExample/Const)]]
	 [[Node: model/input/IteratorGetNext = IteratorGetNext[output_shapes=[[?,16,8], [?], [?,16,8]], output_types=[DT_FLOAT, DT_INT32, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/input/Iterator)]]
